/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        String message = classUnderTest.useMyClass1();
        assertEquals("Hello from MyClass1 in org.foo.example1!", message);
    }
}
