/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.foo.example2.MyClass2;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public String useMyClass2() {
		return new MyClass2().getMessage();
	}
}
