/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.foo.example1.MyClass1;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public String useMyClass1() {
		return new MyClass1().getMessage();
	}
}
