# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          !**/foo
          !**/bar
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Install Foo packages
      run: mvn --file foo.parent/pom.xml install
    - name: Install Bar packages (relocated)
      run: mvn --file bar.parent/pom.xml install
    - name: Test client1 (uses relocated packages)
      run: mvn --file barclient1/pom.xml test
    - name: Test client2 (uses relocated packages)
      run: mvn --file barclient2/pom.xml test